INFO      : 18/07/2019 05:51:42 pm: __init__                       Line: 356 in DQclient.py                         HTTP Client initialised with keyfile: /workspace/PRISE/src/engine/connect/.assimila_dq
ERROR     : 18/07/2019 05:51:42 pm: do                             Line: 84 in dq_db_connect.py                    Unable to execute command INSERT INTO public.product (name, longname, description, keywords, link) VALUES ('LST_GOLD', 'Best LST for PRISE', 'A dataset of temperatures which are always maintained and
  updated when better data comes in. Build from ERA5 and GFS for PRISE.
', 'land surface temperature LST PRISE', 'None');
duplicate key value violates unique constraint "unique_product_link"
DETAIL:  Key (link)=(None) already exists.

WARNING   : 18/07/2019 05:51:42 pm: register                       Line: 41 in registrars.py                       'Unable to execute command INSERT INTO public.product (name, longname, description, keywords, link) VALUES (\'LST_GOLD\', \'Best LST for PRISE\', \'A dataset of temperatures which are always maintained and\n  updated when better data comes in. Build from ERA5 and GFS for PRISE.\n\', \'land surface temperature LST PRISE\', \'None\');\nduplicate key value violates unique constraint "unique_product_link"\nDETAIL:  Key (link)=(None) already exists.\n'
ERROR     : 18/07/2019 05:51:42 pm: register_sub_product           Line: 184 in registration_manager.py             Unable to read LST_GOLD config file from /workspace/PRISE/src/datacube/dq_database/dq_DB_conf/LST_GOLD.yaml
[Errno 2] No such file or directory: '/workspace/PRISE/src/datacube/dq_database/dq_DB_conf/LST_GOLD.yaml'
Traceback (most recent call last):
  File "/workspace/PRISE/src/datacube/dq_database/registration_manager.py", line 178, in register_sub_product
    with open(product_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/PRISE/src/datacube/dq_database/dq_DB_conf/LST_GOLD.yaml'
ERROR     : 18/07/2019 05:51:42 pm: register_product               Line: 127 in registration_manager.py             Product registration failed for LST_GOLD
"Unable to read LST_GOLD config file from /workspace/PRISE/src/datacube/dq_database/dq_DB_conf/LST_GOLD.yaml\n[Errno 2] No such file or directory: '/workspace/PRISE/src/datacube/dq_database/dq_DB_conf/LST_GOLD.yaml'"
